name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        rsync -avz --delete ./ user@your-server:/var/www/my-app

    - name: Install dependencies and restart app
      run: |
        ssh user@your-server << 'EOF'
        cd /var/www/my-app
        # Example commands
        npm install
        pm2 restart app.js
        EOF
